### ISSUE TITLE
Owner and search

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gitea-react-toolkit#19]
I notice that the search forms (in various places) includes an owner text field. I found:
- when I supply an owner with nothing in the search field, nothing happens. I expected a list of repos for the owner
- when I supply a value for the search field, it will return results for across all owners, even if I had supplied a specific owner.

It doesn't seem that the owner field is used at all to filter the search results as I would have expected.

**Comment by klappy** [comment]
This use to function properly on an older release of Gitea. The latest releases that we are using has changed the ability to get a user id which is in the logic to search.

**Comment by elsylambert** [comment]
Owner and search works fine in GiteaReactToolkit  v1.0.0-rc.3.
