### ISSUE TITLE
Retest: FileContext fails if repo has 500 errors

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord/gitea-react-toolkit#30]
Was trying to pick a repo that turns out to have errors, a 500 error if you try to go to https://bg.door43.org/api/v1/repos/richmahn/hi_tn, so when I have selected this repo the FileComponent fails to load. 

Reproduce:
Go to the FileContext component page
Login in and search for richmahn as owner, hi_tn as repo
Click on that repo

**Comment by BincyJ** [comment]
@elsylambert please retest this issue.Thanks.

**Comment by elsylambert** [comment]
Works fine in GiteaReactToolkit v1.1.0-rc.1.
