### ISSUE TITLE
Need to use GRT without Authentication

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gitea-react-toolkit#75]
GRT was broken so it wouldn't allow use without authentication.

**Comment by BincyJ** [comment]
Not testable in tC Create.

**Comment by ancientTexts-net** [comment]
RCL demo:

https://gitea-react-toolkit.netlify.app/

**Comment by ancientTexts-net** [comment]
In the RCL,

https://gitea-react-toolkit.netlify.app/#/Organizations%20?id=currentuserorganizations

- select a demo that requires user to be logged in (e.g., `CurrentUserOrganizations`)
- if you're not logged in, you should see a login prompt
- login, then you should see the correct demo feature (e.g., current user organizations, etc.)

**Comment by cckozie** [comment]
The RCL appears to be working correctly to me

**Comment by elsylambert** [comment]
RCL works fine.
