### ISSUE TITLE
Logout is not working in current version

### ISSUE THREAD

**Issue by vipinpaul** [unfoldingWord/gitea-react-toolkit#79]
Was able to use the `auth.logout();` in the older version (I don't remember the exact version).
But now it is throwing error i.e. 
```
Unhandled Runtime Error
TypeError: auth.logout is not a function
```

**Comment by birchamp** [comment]
@ancientTexts-net Can you paste in the relevant code or a link to it that shows how we're handling this?

**Comment by klappy** [comment]
Has this issue been addressed?
