### ISSUE TITLE
Add prop to allow hiding the RepositoryMenu from ApplicationBar

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/gitea-react-toolkit#82]
To test:
---
- [ ] Open https://deploy-preview-83--gitea-react-toolkit.netlify.app/#/Application%20Bar%20?id=applicationbar
- [ ] Scroll to `view code` and add `hideRepositoryMenu` to `ApplicationBar`
```js
   <ApplicationBar
      hideRepositoryMenu
      title='Application Title'
      buttons={buttons}
      drawerMenu={drawerMenu}
    />
```
- [ ] The RepositoryMenu (Folder Icon) should disappear

**Comment by elsylambert** [comment]
hideRepositoryMenu in the Application Bar works fine.
